resources:
- name: repo
  type: git
  source:
    uri: 
    branch: main

- name: node-hello
  type: registry-image-resource
  source:
    repository: node
    tag: 16.11-buster 
jobs:
- name: test
  plan:
  - get: repo 
  - get: node-hello
    trigger: true
  - task: install
    image: node-hello
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: /bin/bash
        args:
          - -ec
          - |
            cd repo
            npm install
            npm pack